### ISSUE TITLE
Installation fails with postinstall / build script

### ISSUE THREAD

**Issue by PascalAnimateur** [teamfa/sails-hook-webpack#1]
Trying to use this hook in a brand new Sails project (0.12.3) and the installation fails with `Unknown plugin "syntax-export-extensions" specified in (...)/node_modules/sails-hook-webpack/.babelrc`.

Why is the build script `NODE_ENV=production babel src --out-dir lib --copy-files` executed on postinstall? Should that be in the sails project' own package.json instead of here?

Using Node v4.3.2 / npm 3.8.6, will try more recent versions soon.

**Comment by Salakar** [comment]
woops. you're right. that postinstall should not be there. I'll push a new version.

**Comment by Salakar** [comment]
I'll push this in a few hours, i left my laptop charger at work and it's flat. woops.

Feel free to just remove that line from your local copy in the meantime. will solve the issue

**Comment by PascalAnimateur** [comment]
Removing the postinstall, prepublish, build and build-watch from package.json fixes the installation issue, but there's also a typo in the main entry (lib/index.js instead of src/index.js).

Also, you seem to be using ES6 which raises some issues with node 4 (i.e. `import from`)

One last thing (too lazy to open another issue), line 7 should have some kind of check to make sure `sails.config.webpack`is defined or it will raise `Cannot read property 'development' of undefined`

**Comment by Salakar** [comment]
its meant to be es6. the prepublish script compiles to es5 to /lib. so you just need to leave that and set the main back to the lib one, it gets published pre-compiled on npm. it was just that postinstall that shouldn't be there

I've already put in a fix for the config check, not pushed yet, will do soon. I'll be at work in 6ish hours. On phone atm.

**Comment by PascalAnimateur** [comment]
Ok thanks a lot!

**Comment by Salakar** [comment]
managed to do it all on my phone and a remote terminal hah. v2.0.1 published. let me know if all working. thanks

**Comment by Salakar** [comment]
Have confirmed this is working, built: https://github.com/teamfa/sails-universal-react-starter 👍 

Will close this now, but let me know if you experience any more issues.

**Comment by PascalAnimateur** [comment]
I'm having a problem lifting Sails with the following error:

```
(...)/sails-test/node_modules/webpack-dev-middleware/middleware.js:106
            if(err) throw err;
                    ^
Error: invalid argument
    at pathToArray ((...)/Bureau/sails-test/node_modules/memory-fs/lib/MemoryFileSystem.js:44:10)
```

I've create `src/index.js` and this is my `config/webpack.js` :

```
// config/webpack.js
var webpack = require('webpack');

module.exports.webpack = {
    config: {
      entry: "src/index.js",
      output: {
          path: 'assets/js',
          filename: "bundle.js"
      },
      module: {
          loaders: [
              { test: /\.css$/, loader: "style!css" }
          ]
      }
    },  // webpack config here
    development: { // dev server config
      webpack: { }, // separate webpack config for the dev server or defaults to the config above
      config: { // webpack-dev-server-config
        port: 3000
      }
    },
    watchOptions: {
      aggregateTimeout: 300
    }
};
```

Am I missing something in the configuration or is something with ES5 ?
Thanks a lot!

**Comment by Salakar** [comment]
You need to `path.resolve` any provided paths:

``` javascript
// config/webpack.js
var webpack = require('webpack');
var path = require("path");
//
//  __dirnamne - https://nodejs.org/docs/latest/api/globals.html#globals_dirname
//  so this is basically `./config` in this file.
//
module.exports.webpack = {
    config: {
      entry: path.resolve(__dirname, "./../src/"), // go up one from config into the src dir, no need to say index.js
      output: {
          path: path.resolve(__dirname, './../assets/js'),  // go up one from config into the assets dir,
          filename: "bundle.js"
      },
      module: {
          loaders: [
              { test: /\.css$/, loader: "style!css" }
          ]
      }
    },  // webpack config here
    development: { // dev server config
      webpack: { }, // separate webpack config for the dev server or defaults to the config above
      config: { // webpack-dev-server-config
        port: 3000
      }
    },
    watchOptions: {
      aggregateTimeout: 300
    }
};
```

Take a look at the starter link I posted earlier, there's a more in depth webpack config there, might give you some pointers.
